import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-SuisseIntl-Medium h-full w-full`}>{children}</body>
    </html>
  );
}
